version: '3.8'

services:
  task-management-backend:
    build:
      context: .
      dockerfile: task-management-backend/Dockerfile
    container_name: task-management-api
    ports:
      - "8080:8080"
      - "8081:8081"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=DevContainer
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      # For SQLite database persistence
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge
