version: '3'

services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_BASE_URL=http://localhost:8080/api
    ports:
      - "3000:3000"
    networks:
      - task-management-network

networks:
  task-management-network:
    external: true
